(function(){'use strict';
const HDB='healthhub-healthradar-v2',ADB='healthhub-admin-v1',SS='snapshots',AS='audit';let pv=null;
const q=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const prof=()=>localStorage.getItem('hh-profile')==='m'?'monika':'zsolt',toast=s=>{try{window.toast?.(s)}catch{}};
const req=r=>new Promise((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});
const done=t=>new Promise((ok,no)=>{t.oncomplete=ok;t.onerror=()=>no(t.error);t.onabort=()=>no(t.error||Error('Művelet megszakadt'))});
function hdb(){return new Promise((ok,no)=>{let r=indexedDB.open(HDB,1);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function adb(){return new Promise((ok,no)=>{let r=indexedDB.open(ADB,1);r.onupgradeneeded=()=>{let d=r.result;if(!d.objectStoreNames.contains(SS)){let s=d.createObjectStore(SS,{keyPath:'id'});s.createIndex('createdAt','createdAt')}if(!d.objectStoreNames.contains(AS)){let a=d.createObjectStore(AS,{keyPath:'id'});a.createIndex('createdAt','createdAt')}};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function all(){let d=await hdb(),o={};try{for(const n of d.objectStoreNames)o[n]=await req(d.transaction(n).objectStore(n).getAll());return o}finally{d.close()}}
async function audit(action,detail={}){try{let d=await adb(),t=d.transaction(AS,'readwrite');t.objectStore(AS).put({id:'a-'+Date.now()+'-'+Math.random().toString(36).slice(2),createdAt:new Date().toISOString(),action,detail});await done(t);d.close()}catch(e){console.warn(e)}}
async function logs(){let d=await adb();try{return (await req(d.transaction(AS).objectStore(AS).getAll())).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,8)}finally{d.close()}}
async function snaps(){let d=await adb();try{return (await req(d.transaction(SS).objectStore(SS).getAll())).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}finally{d.close()}}
async function snapshot(reason){let x={id:'s-'+Date.now(),createdAt:new Date().toISOString(),reason,data:await all()},d=await adb(),t=d.transaction(SS,'readwrite');t.objectStore(SS).put(x);await done(t);d.close();let a=await snaps();if(a.length>8){d=await adb();t=d.transaction(SS,'readwrite');a.slice(8).forEach(z=>t.objectStore(SS).delete(z.id));await done(t);d.close()}await audit('snapshot',{reason,id:x.id});return x}
async function restoreData(data){let d=await hdb();try{let ns=Object.keys(data).filter(n=>d.objectStoreNames.contains(n));if(!ns.length)throw Error('Nincs visszaállítható adat');let t=d.transaction(ns,'readwrite');for(const n of ns){let s=t.objectStore(n);s.clear();(data[n]||[]).forEach(x=>s.put(x))}await done(t)}finally{d.close()}}
async function undo(){let a=await snaps();if(!a.length)return toast('Nincs snapshot');await snapshot('restore-before-'+a[0].id);await restoreData(a[0].data);await audit('restore',{id:a[0].id});toast('Snapshot visszaállítva');render();window.renderHealthSection?.()}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'')}
function pick(o,as){let m={};Object.keys(o).forEach(k=>m[norm(k)]=o[k]);for(const a of as){let v=m[norm(a)];if(v!==undefined&&v!=='')return v}return null}
function num(v){if(v==null||v==='')return null;let n=Number(String(v).replace(',','.').replace(/[^\d.+-]/g,''));return Number.isFinite(n)?n:null}
function dt(v){let d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16)}
function meas(r,p,src){let d=dt(pick(r,['measuredAt','date','timestamp','time','create_time','start_time']));if(!d)return null;let x={profile:p,measuredAt:d,systolic:num(pick(r,['systolic','sys','high'])),diastolic:num(pick(r,['diastolic','dia','low'])),pulse:num(pick(r,['pulse','heart_rate','heartrate'])),weightKg:num(pick(r,['weightKg','weight','body_weight'])),bloodGlucose:num(pick(r,['bloodGlucose','glucose','blood_glucose'])),oxygenSaturation:num(pick(r,['oxygenSaturation','spo2','oxygen_saturation'])),notes:'Import · '+src,source:'admin-import'};if([x.systolic,x.diastolic,x.pulse,x.weightKg,x.bloodGlucose,x.oxygenSaturation].every(v=>v==null))return null;x.id='imp-'+hash(JSON.stringify(x));return x}
function csv(t){let a=[],r=[],c='',z=false;for(let i=0;i<t.length;i++){let ch=t[i],n=t[i+1];if(ch=='"'&&z&&n=='"'){c+='"';i++;continue}if(ch=='"'){z=!z;continue}if(ch==','&&!z){r.push(c);c='';continue}if((ch=='\n'||ch=='\r')&&!z){if(ch=='\r'&&n=='\n')i++;r.push(c);c='';if(r.some(Boolean))a.push(r);r=[];continue}c+=ch}if(c||r.length){r.push(c);a.push(r)}if(a.length<2)return[];let h=a[0];return a.slice(1).map(x=>Object.fromEntries(h.map((k,i)=>[k,x[i]??''])))}
function fhir(o,p){let out=[];for(const e of o.entry||[]){let r=e.resource;if(!r||r.resourceType!=='Observation')continue;let code=((r.code?.text||'')+' '+(r.code?.coding||[]).map(x=>(x.code||'')+' '+(x.display||'')).join(' ')).toLowerCase(),x={profile:p,measuredAt:dt(r.effectiveDateTime||r.issued),systolic:null,diastolic:null,pulse:null,weightKg:null,bloodGlucose:null,oxygenSaturation:null,notes:'FHIR import',source:'FHIR'};if(!x.measuredAt)continue;if(code.includes('85354-9')||code.includes('blood pressure'))for(const c of r.component||[]){let cc=((c.code?.text||'')+' '+(c.code?.coding||[]).map(y=>(y.code||'')+' '+(y.display||'')).join(' ')).toLowerCase();if(cc.includes('8480-6')||cc.includes('systolic'))x.systolic=num(c.valueQuantity?.value);if(cc.includes('8462-4')||cc.includes('diastolic'))x.diastolic=num(c.valueQuantity?.value)}else if(code.includes('8867-4')||code.includes('heart rate'))x.pulse=num(r.valueQuantity?.value);else if(code.includes('29463-7')||code.includes('body weight'))x.weightKg=num(r.valueQuantity?.value);else if(code.includes('59408-5')||code.includes('2708-6')||code.includes('oxygen saturation'))x.oxygenSaturation=num(r.valueQuantity?.value);else if(code.includes('2339-0')||code.includes('glucose'))x.bloodGlucose=num(r.valueQuantity?.value);else continue;x.id='imp-'+hash(JSON.stringify(x));out.push(x)}return out}
async function parse(file,p){let n=file.name.toLowerCase(),rows=[];if(n.endsWith('.csv'))rows=csv(await file.text()).map(r=>meas(r,p,file.name)).filter(Boolean);else if(n.endsWith('.json')){let o=JSON.parse(await file.text());if(o.resourceType==='Bundle')rows=fhir(o,p);else if(Array.isArray(o))rows=o.map(r=>meas(r,r.profile||p,file.name)).filter(Boolean);else if(Array.isArray(o.measurements))rows=o.measurements.map(r=>meas(r,r.profile||p,file.name)).filter(Boolean);else if(o.data?.measurements)rows=o.data.measurements}else if(n.endsWith('.xlsx')||n.endsWith('.xls'))throw Error('XLSX adapterhely kész, aktiválás következik. Most CSV-be exportáld.');else if(n.endsWith('.zip'))throw Error('Samsung Health ZIP adapterhely kész, aktiválás következik.');else throw Error('Támogatott: CSV, JSON, FHIR JSON');let d=await hdb(),old=[];try{old=await req(d.transaction('measurements').objectStore('measurements').getAll())}finally{d.close()}let ids=new Set(old.map(x=>x.id)),nu=rows.filter(x=>!ids.has(x.id)),du=rows.filter(x=>ids.has(x.id));return{file:file.name,profile:p,rows,nu,du}}
async function commit(){if(!pv?.nu.length)return toast('Nincs új rekord');let s;try{s=await snapshot('before-import-'+pv.file)}catch(e){return toast('Import leállítva: snapshot hiba')}let d=await hdb();try{let t=d.transaction('measurements','readwrite'),os=t.objectStore('measurements');pv.nu.forEach(x=>os.put(x));await done(t)}finally{d.close()}await audit('import',{file:pv.file,profile:pv.profile,imported:pv.nu.length,duplicates:pv.du.length,snapshot:s.id});toast(pv.nu.length+' rekord importálva');pv=null;render();window.renderHealthSection?.()}
function dl(b,n){let a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)}
async function exjson(){let d=await all();delete d.documentBlobs;dl(new Blob([JSON.stringify({healthhubAdminExport:true,exportedAt:new Date().toISOString(),data:d},null,2)],{type:'application/json'}),'HealthHub_structured.json');audit('export_json')}
async function excsv(){let p=document.getElementById('haProf')?.value||prof(),d=await hdb(),r=[];try{r=await req(d.transaction('measurements').objectStore('measurements').index('profile').getAll(p))}finally{d.close()}let h=['id','profile','measuredAt','systolic','diastolic','pulse','weightKg','bloodGlucose','oxygenSaturation','notes'],e=v=>{v=String(v??'');return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v},t=h.join(',')+'\n'+r.map(x=>h.map(k=>e(x[k])).join(',')).join('\n');dl(new Blob([t],{type:'text/csv'}),'HealthHub_'+p+'_measurements.csv');audit('export_csv',{profile:p,count:r.length})}
async function render(){let b=document.getElementById('haBody');if(!b)return;let l=await logs(),s=await snaps();b.innerHTML='<div class="haGrid"><section><h3>📥 Import Center</h3><select id="haProf"><option value="monika" '+(prof()=='monika'?'selected':'')+'>Mónika</option><option value="zsolt" '+(prof()=='zsolt'?'selected':'')+'>Zsolt</option></select><button onclick="haPick()">Fájl kiválasztása</button><small>Aktív: CSV · JSON · FHIR JSON. XLSX és Samsung ZIP következő adapter.</small></section><section><h3>📤 Export Center</h3><button onclick="haCsv()">Mérések CSV</button><button onclick="haJson()">Strukturált JSON</button><button onclick="window.exportHealthVault?.()">Teljes TAR backup</button></section><section><h3>🛡 Biztonság</h3><button onclick="haSnap()">Snapshot most</button><button onclick="haUndo()">Utolsó snapshot visszaállítása</button><small>'+(s[0]?'Legutóbbi: '+q(new Date(s[0].createdAt).toLocaleString('hu-HU')):'Még nincs snapshot')+'</small></section><section><h3>🧩 Adapterek</h3><small>CSV ✅ · JSON ✅ · FHIR ✅ · Samsung ZIP ⏳ · XLSX ⏳ · SQLite/HL7 később</small></section></div>'+(pv?'<div class="haPrev"><b>👁 '+q(pv.file)+'</b><p>Új: '+pv.nu.length+' · Duplikátum: '+pv.du.length+' · Összes: '+pv.rows.length+'</p><button onclick="haCommit()">Importálás most</button></div>':'')+'<section class="haLog"><h3>📋 Audit log</h3>'+l.map(x=>'<div>'+q(new Date(x.createdAt).toLocaleString('hu-HU'))+' · <b>'+q(x.action)+'</b></div>').join('')+'</section>'}
function ui(){if(document.getElementById('haStyle'))return;let s=document.createElement('style');s.id='haStyle';s.textContent='.haFab{position:fixed;right:14px;bottom:82px;z-index:95;border:0;border-radius:16px;background:#173f62;color:#fff;padding:10px 13px;font-weight:850}.haOv{position:fixed;inset:0;z-index:240;background:#08203388;display:none;align-items:flex-end;justify-content:center}.haOv.on{display:flex}.haSheet{width:min(100vw,820px);max-height:94vh;overflow:auto;background:#f4f8fb;border-radius:25px 25px 0 0;padding:14px}.haTop{display:flex;justify-content:space-between}.haGrid{display:grid;grid-template-columns:1fr;gap:9px}@media(min-width:720px){.haGrid{grid-template-columns:1fr 1fr}}.haGrid section,.haPrev,.haLog{background:#fff;border-radius:16px;padding:12px;margin-top:9px}.haGrid h3,.haLog h3{margin:0 0 8px;color:#173f62}.haGrid button,.haPrev button,.haGrid select{border:1px solid #d9e4ec;background:#f7fafc;color:#2c506c;border-radius:11px;padding:8px;margin:3px;font-weight:750}.haGrid small,.haLog div{display:block;font-size:8px;color:#73879a;margin-top:6px}';document.head.appendChild(s);let f=document.createElement('button');f.className='haFab';f.textContent='⚙ Admin';f.onclick=()=>haOpen();document.body.appendChild(f);let o=document.createElement('div');o.id='haOv';o.className='haOv';o.innerHTML='<div class="haSheet"><div class="haTop"><div><small>HEALTHHUB · DATA GATEWAY</small><h2>Admin Data Hub</h2></div><button onclick="haClose()">×</button></div><div id="haBody"></div></div>';o.onclick=e=>{if(e.target===o)haClose()};document.body.appendChild(o);let i=document.createElement('input');i.id='haFile';i.type='file';i.accept='.csv,.json,.xlsx,.xls,.zip';i.hidden=true;i.onchange=async e=>{let f=e.target.files?.[0];e.target.value='';if(!f)return;try{pv=await parse(f,document.getElementById('haProf')?.value||prof());await audit('preview',{file:f.name,newCount:pv.nu.length,duplicates:pv.du.length});render()}catch(x){toast('Import előnézet hiba: '+(x.message||x))}};document.body.appendChild(i)}
window.haOpen=()=>{ui();document.getElementById('haOv').classList.add('on');render()};window.haClose=()=>document.getElementById('haOv')?.classList.remove('on');window.haPick=()=>document.getElementById('haFile').click();window.haCommit=commit;window.haSnap=async()=>{try{await snapshot('manual');toast('Snapshot kész');render()}catch(e){toast('Snapshot hiba')}};window.haUndo=undo;window.haJson=exjson;window.haCsv=excsv;
ui();document.documentElement.dataset.healthhubAdmin='1.37';window.HH_LIVE_BUILD='v1.37-admin-data-hub';
})();