const $=id=>document.getElementById(id);
const img=$('ticketImage'),empty=$('emptyState'),label=$('sideLabel');
const frontBtn=$('frontBtn'),backBtn=$('backBtn'),newBtn=$('newBtn');
const sheet=$('captureSheet'),closeBtn=$('closeSheet'),cancelBtn=$('cancelBtn');
const capFront=$('captureFront'),capBack=$('captureBack');
const frontInput=$('frontInput'),backInput=$('backInput');
const frontStatus=$('frontStatus'),backStatus=$('backStatus'),saveBtn=$('saveBtn'),processing=$('processing');
let side='front',staged={front:null,back:null},saved={front:null,back:null},activeUrl=null,wakeLock=null;
const DB='berlet-db',STORE='images';
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbSet(k,v){const db=await openDb();await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v,k);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close()}
async function dbGet(k){const db=await openDb();const v=await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readonly');const r=tx.objectStore(STORE).get(k);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)});db.close();return v}
function render(which){side=which;frontBtn.classList.toggle('active',which==='front');backBtn.classList.toggle('active',which==='back');label.textContent=which==='front'?'ELEJE':'HÁTULJA';if(activeUrl)URL.revokeObjectURL(activeUrl);const b=saved[which];if(b){activeUrl=URL.createObjectURL(b);img.src=activeUrl;img.style.display='block';empty.style.display='none'}else{img.removeAttribute('src');img.style.display='none';empty.style.display='block'}}
async function load(){saved.front=await dbGet('front');saved.back=await dbGet('back');render('front')}
function updateCapture(){const f=!!staged.front,b=!!staged.back;capFront.classList.toggle('ready',f);capBack.classList.toggle('ready',b);frontStatus.textContent=f?'✓ Kép rendben':'Nincs kép';backStatus.textContent=b?'✓ Kép rendben':'Nincs kép';saveBtn.disabled=!(f&&b)}
function openSheet(){staged={front:null,back:null};updateCapture();sheet.classList.remove('hidden')}
function closeSheet(){sheet.classList.add('hidden');staged={front:null,back:null};frontInput.value='';backInput.value=''}
function avgBorder(data,w,h){let r=0,g=0,b=0,n=0;const take=(x,y)=>{const i=(y*w+x)*4;r+=data[i];g+=data[i+1];b+=data[i+2];n++};for(let x=0;x<w;x+=4){take(x,0);take(x,h-1)}for(let y=0;y<h;y+=4){take(0,y);take(w-1,y)}return[r/n,g/n,b/n]}
function autoBounds(c){const max=420,s=Math.min(1,max/Math.max(c.width,c.height)),w=Math.max(40,Math.round(c.width*s)),h=Math.max(40,Math.round(c.height*s));const t=document.createElement('canvas');t.width=w;t.height=h;const x=t.getContext('2d',{willReadFrequently:true});x.drawImage(c,0,0,w,h);const im=x.getImageData(0,0,w,h),d=im.data,bg=avgBorder(d,w,h);let minX=w,minY=h,maxX=0,maxY=0,count=0;for(let y=0;y<h;y+=2){for(let xx=0;xx<w;xx+=2){const i=(y*w+xx)*4;const diff=Math.abs(d[i]-bg[0])+Math.abs(d[i+1]-bg[1])+Math.abs(d[i+2]-bg[2]);if(diff>85){minX=Math.min(minX,xx);maxX=Math.max(maxX,xx);minY=Math.min(minY,y);maxY=Math.max(maxY,y);count++}}}if(!count||maxX-minX<w*.35||maxY-minY<h*.2){minX=w*.04;maxX=w*.96;minY=h*.04;maxY=h*.96}const padX=(maxX-minX)*.03,padY=(maxY-minY)*.04;minX=Math.max(0,minX-padX);minY=Math.max(0,minY-padY);maxX=Math.min(w,maxX+padX);maxY=Math.min(h,maxY+padY);return{x:Math.round(minX/s),y:Math.round(minY/s),w:Math.round((maxX-minX)/s),h:Math.round((maxY-minY)/s)}}
async function processFile(file){const bm=await createImageBitmap(file,{imageOrientation:'from-image'});const max=2000,s=Math.min(1,max/Math.max(bm.width,bm.height));const c=document.createElement('canvas');c.width=Math.round(bm.width*s);c.height=Math.round(bm.height*s);const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(bm,0,0,c.width,c.height);bm.close();const b=autoBounds(c);const out=document.createElement('canvas'),scale=Math.min(1,1800/Math.max(b.w,b.h));out.width=Math.max(1,Math.round(b.w*scale));out.height=Math.max(1,Math.round(b.h*scale));const o=out.getContext('2d');o.fillStyle='#fff';o.fillRect(0,0,out.width,out.height);o.imageSmoothingEnabled=true;o.imageSmoothingQuality='high';o.drawImage(c,b.x,b.y,b.w,b.h,0,0,out.width,out.height);return new Promise((res,rej)=>out.toBlob(v=>v?res(v):rej(new Error('Képfeldolgozási hiba')),'image/jpeg',.92))}
async function handle(file,which){if(!file)return;processing.classList.remove('hidden');try{staged[which]=await processFile(file);updateCapture()}catch(e){console.error(e);alert('A kép feldolgozása nem sikerült. Fotózd le újra.')}finally{processing.classList.add('hidden')}}
async function save(){if(!staged.front||!staged.back)return;processing.classList.remove('hidden');try{await dbSet('front',staged.front);await dbSet('back',staged.back);saved={front:staged.front,back:staged.back};closeSheet();render('front')}catch(e){console.error(e);alert('A bérlet mentése nem sikerült.')}finally{processing.classList.add('hidden')}}
async function keepAwake(){try{if('wakeLock'in navigator&&document.visibilityState==='visible')wakeLock=await navigator.wakeLock.request('screen')}catch(e){}}
frontBtn.onclick=()=>render('front');backBtn.onclick=()=>render('back');newBtn.onclick=openSheet;closeBtn.onclick=closeSheet;cancelBtn.onclick=closeSheet;capFront.onclick=()=>frontInput.click();capBack.onclick=()=>backInput.click();frontInput.onchange=e=>handle(e.target.files?.[0],'front');backInput.onchange=e=>handle(e.target.files?.[0],'back');saveBtn.onclick=save;img.onclick=()=>render(side==='front'?'back':'front');document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')keepAwake()});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));load().catch(console.error);keepAwake();
